name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - "1.*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push Docker image
        run: |
          export CA_PAT=${{ secrets.PERSONAL_TOKEN }}
          echo $CA_PAT | docker login ghcr.io -u nowzarifarhad --password-stdin
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/fdn-theme:$PACKAGE_VERSION
            docker push ghcr.io/${{ github.repository_owner }}/fdn-theme:$PACKAGE_VERSION
      
