name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "1.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
      - run: export CA_PAT=secrets.PERSONAL_TOKEN
      - run: docker login ghcr.io -u nowzarifarhad --password-stdin
      - run: docker build . --file Dockerfile --tag ghcr.io/nowzarifarhad/fdn-theme:$PACKAGE_VERSION
      - run: docker push ghcr.io/nowzarifarhad/fdn-theme:$PACKAGE_VERSION
      
